package com.alphaStore.alphaS3.utils.redis

import org.springframework.stereotype.Component

@Component
class RedisCredentials {
    val REDIS_HOST = "192.168.0.1"
    val REDIS_PORT = 6379
    val REDIS_PASSWORD: String = "password"

    val REDIS_KEY_BLACKLISTED_IPS = "ALPHA_STORE_REDIS_KEY_BLACKLISTED_IPS"
    val REDIS_KEY_WHITELISTED_IPS = "ALPHA_STORE_REDIS_KEY_WHITELISTED_IPS"
    val REDIS_KEY_JWT_BLACK_LIST = "ALPHA_STORE_REDIS_KEY_JWT_BLACK_LIST"
    val REDIS_KEY_ACCESS_ROLE = "ALPHA_STORE_REDIS_KEY_ACCESS_ROLE"
    val REDIS_KEY_USER_SERIAL = "ALPHA_STORE_REDIS_KEY_USER_SERIAL"
    val REDIS_KEY_ACCESS_CONTROL = "ALPHA_STORE_REDIS_KEY_ACCESS_CONTROL"
    val REDIS_KEY_DATABASE_RESULT = "ALPHA_STORE_REDIS_KEY_DATABASE_RESULT"
    val REDIS_KEY_RESULT = "ALPHA_STORE_REDIS_KEY_RESULT"
    val REDIS_KEY_DATABASE_TABLE_LOCK = "ALPHA_STORE_REDIS_KEY_DATABASE_TABLE_LOCK"
}